package excepciones_I;

import java.io.IOException;
import java.util.InputMismatchException;
import java.util.Scanner;

public class EntradaDatos {

	public static void main(String[] args) {

		System.out.println("¿Qué deseas haces?");
		System.out.println("1. Introducir datos");
		System.out.println("2. Salir del programa");

		Scanner entrada = new Scanner(System.in);
		int desicion = entrada.nextInt();
		if (desicion == 1) {
//			try {
				
				pedirDatos();
//			} catch (Exception e) {
								
//				System.out.println("Qué demonios has introducido en la edad?");
//			}
		} else {
			System.out.println("Adios");
			System.exit(0);
		}
		entrada.close();

	}

	static void pedirDatos() throws IOException {

//		try {
			Scanner entrada = new Scanner(System.in);
			System.out.println("Intoduce tu nombre, por favor");
			String nombreUsuario = entrada.nextLine();
			System.out.println("Introduce edad, por favor ");
			int edad = entrada.nextInt();
			System.out.println("Hola " + nombreUsuario + ". El año que viene trandrás " + (edad + 1) + " años");
			entrada.close();
//		} catch (InputMismatchException e) {

//			System.out.println("Qué demonios has introducido en la edad?");
//		}
		System.out.println("Hemos terminado");
	}

}
